// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zputxsuvztizgfwioizc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwdXR4c3V2enRpemdmd2lvaXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDk4NzMsImV4cCI6MjA2MTAyNTg3M30.-aJVT6ImIKWMonVL3KQ0XsDGHha6E2GilORtkYEbbBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);